### ISSUE TITLE
How to handle undefined?

### ISSUE THREAD

**Issue by darr1s** [drwpow/openapi-fetch#40]
**Description**

Coming from `openapi-generator/typescript-fetch`, this library seems to wrap all response data with possibly undefined.

**Reproduction**

In latest v0.1.0,

<img width="601" alt="image" src="https://user-images.githubusercontent.com/21124691/235935323-da5f2234-3b10-4932-b439-089960e831d6.png">

**Expected result**

Unsure, TBD

**Checklist**

- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/drwpow/openapi-fetch/blob/main/CONTRIBUTING.md))

**Comment by drwpow** [comment]
See the README—it gives instructions. It’s only `| undefined` because you may have an error. as soon as you handle the error, `data` will be defined.

Also check your OpenAPI schema—most people don’t realize that by default, OpenAPI marks all properties as optional. Be sure your schema has `required: true` specified on the response or on the top-level object.

**Comment by darr1s** [comment]
Thanks, it does seems like we do not need to use try {} catch {}.

For those who doesn't know, as long as we do

```
const { data, error } = apiClient.get(...)
if (error) throw Error
return data
```

Then data will not be undefined.

**Comment by drwpow** [comment]
That’s one way of dealing with it! This is my opinion, but personally I wouldn’t `throw`, especially because the `error` object has useful data returned from your API on what went wrong. It’s probably better to show that to the user than simply throwing an exception they won’t be able to act upon 🙂
