### ISSUE TITLE
Svelte custom fetch

### ISSUE THREAD

**Issue by ESchouten** [drwpow/openapi-fetch#47]
Svelte provides a [custom fetch](https://kit.svelte.dev/docs/load#making-fetch-requests) in their load functions which you have to use in order to use SSR and their middleware handlers.
For this library Svelte is listed as supported, but I can't figure out how this Svelte fetch is used. Are there examples? Or is this underway?

**Comment by drwpow** [comment]
This is a great idea! I’m actually working on building out more of a [docs site](https://openapi-ts.pages.dev) right now, and framework-specific examples should definitely be added.

**Comment by drwpow** [comment]
But also there probably are some caveats with language-specific things. For example, in React/React Router, there are [loaders](https://reactrouter.com/en/main/route/loader) that can be used to load data on route change (which can be handy for things like auth), however, this is incompatible with `openapi-fetch` because there’s no way to maintain the type inference through the entire React Router layer (same goes for a typed GraphQL wrapper, or anything else, for that matter).

But again, it would still help to have framework examples along with notes about what does/doesn’t work well for each framework (but as a general rule, openapi-fetch will probably work the exact same way a typed GraphQL client will)
